default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: password

development:
  <<: *default
  database: el_capitan_development

test:
  <<: *default
  database: el_capitan_test

production:
  <<: *default
  database: el_capitan_production


