#branches
lima     = Branch.find_or_create_by(name: "Lima", code:"LIM20161", address: "Av. José Pardo 601, piso 11 oficina 1104, Miraflores")
mexico   = Branch.find_or_create_by(name: "México", code: "MEX20161", address: "Calle Campeche 280, Int. 303, Hipódromo Condesa")
santiago = Branch.find_or_create_by(name: "Chile", code: "CHI20161", address: "Av. Puma 1180, Recoleta (IF Blanco)")
arequipa = Branch.find_or_create_by(name: "Arequipa", code: "AQP20161", address: "Av. salaverry S/N, Lara - Socabaya (Ref. a una cuadra del club el golf y al costado del colegio Santisimo Salvador)")

#groups
Group.find_or_create_by(name: "LIM20141", description: "Promoción LIM20141", branch: lima)
Group.find_or_create_by(name: "LIM20151", description: "Promoción LIM20151", branch: lima)
Group.find_or_create_by(name: "LIM20152", description: "Promoción LIM20152", branch: lima)
Group.find_or_create_by(name: "LIM20161", description: "Promoción LIM20161", branch: lima)
Group.find_or_create_by(name: "LIM20162", description: "Promoción LIM20162", branch: lima)
Group.find_or_create_by(name: "SCL20151", description: "Promoción SCL20151", branch: santiago)
Group.find_or_create_by(name: "SCL20161", description: "Promoción SCL20161", branch: santiago)
Group.find_or_create_by(name: "SCL20162", description: "Promoción SCL20162", branch: santiago)
Group.find_or_create_by(name: "MEX20151", description: "Promoción MEX20151", branch: mexico)
Group.find_or_create_by(name: "MEX20161", description: "Promoción MEX20161", branch: mexico)
Group.find_or_create_by(name: "MEX20162", description: "Promoción MEX20162", branch: mexico)
Group.find_or_create_by(name: "AQP20151", description: "Promoción AQP20151", branch: arequipa)
Group.find_or_create_by(name: "AQP20161", description: "Promoción AQP20161", branch: arequipa)
Group.find_or_create_by(name: "AQP20162", description: "Promoción AQP20162", branch: arequipa)

#districts
District.find_or_create_by(name: "Ancón", branch:lima)
District.find_or_create_by(name: "Ate", branch:lima)
District.find_or_create_by(name: "Barranco", branch:lima)
District.find_or_create_by(name: "Bellavista", branch:lima)
District.find_or_create_by(name: "Breña", branch:lima)
District.find_or_create_by(name: "Callao", branch:lima)
District.find_or_create_by(name: "Carabayllo", branch:lima)
District.find_or_create_by(name: "Carmen de la Legua - Reynoso", branch:lima)
District.find_or_create_by(name: "Chaclacayo", branch:lima)
District.find_or_create_by(name: "Chorrillos", branch:lima)
District.find_or_create_by(name: "Chosica", branch:lima)
District.find_or_create_by(name: "Cieneguilla", branch:lima)
District.find_or_create_by(name: "Comas", branch:lima)
District.find_or_create_by(name: "El Agustino", branch:lima)
District.find_or_create_by(name: "Independencia", branch:lima)
District.find_or_create_by(name: "Jesús María", branch:lima)
District.find_or_create_by(name: "La Molina", branch:lima)
District.find_or_create_by(name: "La Perla", branch:lima)
District.find_or_create_by(name: "La Punta", branch:lima)
District.find_or_create_by(name: "La Victoria", branch:lima)
District.find_or_create_by(name: "Lima", branch:lima)
District.find_or_create_by(name: "Lince", branch:lima)
District.find_or_create_by(name: "Los Olivos", branch:lima)
District.find_or_create_by(name: "Lurín", branch:lima)
District.find_or_create_by(name: "Magdalena del Mar", branch:lima)
District.find_or_create_by(name: "Miraflores", branch:lima)
District.find_or_create_by(name: "Pachacamac", branch:lima)
District.find_or_create_by(name: "Pucusana", branch:lima)
District.find_or_create_by(name: "Pueblo Libre", branch:lima)
District.find_or_create_by(name: "Puente Piedra", branch:lima)
District.find_or_create_by(name: "Punta Hermosa", branch:lima)
District.find_or_create_by(name: "Punta Negra", branch:lima)
District.find_or_create_by(name: "Rimac", branch:lima)
District.find_or_create_by(name: "San Bartolo", branch:lima)
District.find_or_create_by(name: "San Borja", branch:lima)
District.find_or_create_by(name: "San Isidro", branch:lima)
District.find_or_create_by(name: "San Juan de Lurigancho", branch:lima)
District.find_or_create_by(name: "San Juan de Miraflores", branch:lima)
District.find_or_create_by(name: "San Luis", branch:lima)
District.find_or_create_by(name: "San Martín de Porres", branch:lima)
District.find_or_create_by(name: "San Miguel", branch:lima)
District.find_or_create_by(name: "Santa Anita", branch:lima)
District.find_or_create_by(name: "Santa María del Mar", branch:lima)
District.find_or_create_by(name: "Santa Rosa", branch:lima)
District.find_or_create_by(name: "Santiago de Surco", branch:lima)
District.find_or_create_by(name: "Surquillo", branch:lima)
District.find_or_create_by(name: "Ventanilla", branch:lima)
District.find_or_create_by(name: "Villa el Salvador", branch:lima)
District.find_or_create_by(name: "Villa María del Triunfo", branch:lima)
District.find_or_create_by(name: "Otro distrito / ciudad", branch: lima)

District.find_or_create_by(name: "Acambay", branch:mexico)
District.find_or_create_by(name: "Acolman", branch:mexico)
District.find_or_create_by(name: "Aculco", branch:mexico)
District.find_or_create_by(name: "Almoloya de Alquisiras", branch:mexico)
District.find_or_create_by(name: "Almoloya de Juárez", branch:mexico)
District.find_or_create_by(name: "Almoloya del Río", branch:mexico)
District.find_or_create_by(name: "Alvaro Obregón", branch:mexico)
District.find_or_create_by(name: "Amanalco", branch:mexico)
District.find_or_create_by(name: "Amatepec", branch:mexico)
District.find_or_create_by(name: "Amecameca", branch:mexico)
District.find_or_create_by(name: "Apaxco", branch:mexico)
District.find_or_create_by(name: "Atenco", branch:mexico)
District.find_or_create_by(name: "Atizapán", branch:mexico)
District.find_or_create_by(name: "Atizapán de Zaragoza", branch:mexico)
District.find_or_create_by(name: "Atlacomulco", branch:mexico)
District.find_or_create_by(name: "Atlautla", branch:mexico)
District.find_or_create_by(name: "Axapusco", branch:mexico)
District.find_or_create_by(name: "Ayapango", branch:mexico)
District.find_or_create_by(name: "Azcapotzalco", branch:mexico)
District.find_or_create_by(name: "Benito Juárez", branch:mexico)
District.find_or_create_by(name: "Calimaya", branch:mexico)
District.find_or_create_by(name: "Capulhuac", branch:mexico)
District.find_or_create_by(name: "Chalco", branch:mexico)
District.find_or_create_by(name: "Chapa de Mota", branch:mexico)

District.find_or_create_by(name: "Chapultepec", branch:mexico)
District.find_or_create_by(name: "Chiautla", branch:mexico)
District.find_or_create_by(name: "Chicoloapan", branch:mexico)
District.find_or_create_by(name: "Chiconcuac", branch:mexico)
District.find_or_create_by(name: "Chimalhuacán", branch:mexico)
District.find_or_create_by(name: "Coacalco de Berriozábal", branch:mexico)
District.find_or_create_by(name: "Coatepec Harinas", branch:mexico)
District.find_or_create_by(name: "Cocotitlán", branch:mexico)
District.find_or_create_by(name: "Coyoacán", branch:mexico)
District.find_or_create_by(name: "Coyotepec", branch:mexico)
District.find_or_create_by(name: "Cuajimalpa de Morelos", branch:mexico)
District.find_or_create_by(name: "Cuáuhtemoc", branch:mexico)
District.find_or_create_by(name: "Cuautitlán", branch:mexico)
District.find_or_create_by(name: "Cuautitlán Izcalli", branch:mexico)
District.find_or_create_by(name: "Donato Guerra", branch:mexico)
District.find_or_create_by(name: "Ecatepec de Morelos", branch:mexico)
District.find_or_create_by(name: "Ecatzingo", branch:mexico)
District.find_or_create_by(name: "El Oro", branch:mexico)
District.find_or_create_by(name: "Gustavo A. Madero", branch:mexico)
District.find_or_create_by(name: "Huehuetoca", branch:mexico)
District.find_or_create_by(name: "Hueypoxtla", branch:mexico)
District.find_or_create_by(name: "Huixquilucan", branch:mexico)
District.find_or_create_by(name: "Isidro Fabela", branch:mexico)
District.find_or_create_by(name: "Ixtapaluca", branch:mexico)
District.find_or_create_by(name: "Ixtapan de la Sal", branch:mexico)
District.find_or_create_by(name: "Ixtapan del Oro", branch:mexico)
District.find_or_create_by(name: "Ixtlahuaca", branch:mexico)
District.find_or_create_by(name: "Iztacalco", branch:mexico)
District.find_or_create_by(name: "Iztapalapa", branch:mexico)
District.find_or_create_by(name: "Jaltenco", branch:mexico)
District.find_or_create_by(name: "Jilotepec", branch:mexico)
District.find_or_create_by(name: "Jilotzingo", branch:mexico)
District.find_or_create_by(name: "Jiquipilco", branch:mexico)
District.find_or_create_by(name: "Jocotitlán", branch:mexico)
District.find_or_create_by(name: "Joquicingo", branch:mexico)
District.find_or_create_by(name: "Juchitepec", branch:mexico)
District.find_or_create_by(name: "La Magdalena Contreras", branch:mexico)
District.find_or_create_by(name: "La Paz", branch:mexico)
District.find_or_create_by(name: "Lerma", branch:mexico)
District.find_or_create_by(name: "Luvianos", branch:mexico)
District.find_or_create_by(name: "Malinalco", branch:mexico)
District.find_or_create_by(name: "Melchor Ocampo", branch:mexico)
District.find_or_create_by(name: "Metepec", branch:mexico)
District.find_or_create_by(name: "Mexicaltzingo", branch:mexico)
District.find_or_create_by(name: "Miguel Hidalgo", branch:mexico)
District.find_or_create_by(name: "Milpa Alta", branch:mexico)
District.find_or_create_by(name: "Morelos", branch:mexico)
District.find_or_create_by(name: "Naucalpan de Juárez", branch:mexico)
District.find_or_create_by(name: "Nezahualcóyotl", branch:mexico)
District.find_or_create_by(name: "Nextlalpan", branch:mexico)
District.find_or_create_by(name: "Nicolás Romero", branch:mexico)
District.find_or_create_by(name: "Nopaltepec", branch:mexico)
District.find_or_create_by(name: "Ocoyoacac", branch:mexico)
District.find_or_create_by(name: "Ocuilan", branch:mexico)
District.find_or_create_by(name: "Otumba", branch:mexico)
District.find_or_create_by(name: "Otzoloapan", branch:mexico)
District.find_or_create_by(name: "Otzolotepec", branch:mexico)
District.find_or_create_by(name: "Ozumba", branch:mexico)
District.find_or_create_by(name: "Papalotla", branch:mexico)
District.find_or_create_by(name: "Polotitlán", branch:mexico)
District.find_or_create_by(name: "Rayón", branch:mexico)
District.find_or_create_by(name: "San Antonio la Isla", branch:mexico)
District.find_or_create_by(name: "San Felipe del Progreso", branch:mexico)
District.find_or_create_by(name: "San José del Rincón", branch:mexico)
District.find_or_create_by(name: "San Martín de las Pirámides", branch:mexico)
District.find_or_create_by(name: "San Mateo Atenco", branch:mexico)
District.find_or_create_by(name: "San Simón de Guerrero", branch:mexico)
District.find_or_create_by(name: "Santo Tomás", branch:mexico)
District.find_or_create_by(name: "Soyaniquilpan de Juárez", branch:mexico)
District.find_or_create_by(name: "Sultepec", branch:mexico)
District.find_or_create_by(name: "Tecámac", branch:mexico)
District.find_or_create_by(name: "Tejupilco", branch:mexico)
District.find_or_create_by(name: "Temamatla", branch:mexico)
District.find_or_create_by(name: "Temascalapa", branch:mexico)
District.find_or_create_by(name: "Temascalcingo", branch:mexico)
District.find_or_create_by(name: "Temascaltepec", branch:mexico)
District.find_or_create_by(name: "Temoaya", branch:mexico)
District.find_or_create_by(name: "Tenancingo", branch:mexico)
District.find_or_create_by(name: "Tenango del Aire", branch:mexico)
District.find_or_create_by(name: "Tenango del Valle", branch:mexico)
District.find_or_create_by(name: "Teoloyucán", branch:mexico)
District.find_or_create_by(name: "Teotihuacán", branch:mexico)
District.find_or_create_by(name: "Tepetlaoxtoc", branch:mexico)
District.find_or_create_by(name: "Tepetlixpa", branch:mexico)
District.find_or_create_by(name: "Tepotzotlán", branch:mexico)
District.find_or_create_by(name: "Tequixquiac", branch:mexico)
District.find_or_create_by(name: "Texcaltitlán", branch:mexico)
District.find_or_create_by(name: "Texcalyacac", branch:mexico)
District.find_or_create_by(name: "Texcoco", branch:mexico)
District.find_or_create_by(name: "Tezoyuca", branch:mexico)
District.find_or_create_by(name: "Tianguistenco", branch:mexico)
District.find_or_create_by(name: "Timilpan", branch:mexico)
District.find_or_create_by(name: "Tláhuac", branch:mexico)
District.find_or_create_by(name: "Tlalmanalco", branch:mexico)
District.find_or_create_by(name: "Tlalnepantla de Baz", branch:mexico)
District.find_or_create_by(name: "Tlalpan", branch:mexico)
District.find_or_create_by(name: "Tlatlaya", branch:mexico)
District.find_or_create_by(name: "Toluca", branch:mexico)
District.find_or_create_by(name: "Tonanitla", branch:mexico)
District.find_or_create_by(name: "Tonatico", branch:mexico)
District.find_or_create_by(name: "Tultepec", branch:mexico)
District.find_or_create_by(name: "Tultitlán", branch:mexico)
District.find_or_create_by(name: "Valle de Bravo", branch:mexico)
District.find_or_create_by(name: "Valle de Chalco Solidaridad", branch:mexico)
District.find_or_create_by(name: "Venustiano Carranza", branch:mexico)
District.find_or_create_by(name: "Villa de Allende", branch:mexico)
District.find_or_create_by(name: "Villa del Carbón", branch:mexico)
District.find_or_create_by(name: "Villa Guerrero", branch:mexico)
District.find_or_create_by(name: "Villa Victoria", branch:mexico)
District.find_or_create_by(name: "Xalatlaco", branch:mexico)
District.find_or_create_by(name: "Xochimilco", branch:mexico)
District.find_or_create_by(name: "Xonacatlán", branch:mexico)
District.find_or_create_by(name: "Zacazonapan", branch:mexico)
District.find_or_create_by(name: "Zacualpan", branch:mexico)
District.find_or_create_by(name: "Zinacantepec", branch:mexico)
District.find_or_create_by(name: "Zumpahuacán", branch:mexico)
District.find_or_create_by(name: "Zumpango", branch:mexico)
District.find_or_create_by(name: "Otra delegación / ciudad", branch: mexico)

District.find_or_create_by(name: "Cerrillos", branch:santiago)
District.find_or_create_by(name: "Cerro Navia", branch:santiago)
District.find_or_create_by(name: "Conchalí", branch:santiago)
District.find_or_create_by(name: "El Bosque", branch:santiago)
District.find_or_create_by(name: "Estación Central", branch:santiago)
District.find_or_create_by(name: "Huechuraba", branch:santiago)
District.find_or_create_by(name: "Independencia", branch:santiago)
District.find_or_create_by(name: "La Cisterna", branch:santiago)
District.find_or_create_by(name: "La Florida", branch:santiago)
District.find_or_create_by(name: "La Granja", branch:santiago)
District.find_or_create_by(name: "La Pintana", branch:santiago)
District.find_or_create_by(name: "La Reina", branch:santiago)
District.find_or_create_by(name: "Las Condes", branch:santiago)
District.find_or_create_by(name: "Lo Barnechea", branch:santiago)
District.find_or_create_by(name: "Lo Espejo", branch:santiago)
District.find_or_create_by(name: "Lo Prado", branch:santiago)
District.find_or_create_by(name: "Macul", branch:santiago)
District.find_or_create_by(name: "Maipú", branch:santiago)
District.find_or_create_by(name: "Ñuñoa", branch:santiago)
District.find_or_create_by(name: "Padre Hurtado", branch:santiago)
District.find_or_create_by(name: "Pedro Aguirre Cerda", branch:santiago)
District.find_or_create_by(name: "Peñalolén", branch:santiago)
District.find_or_create_by(name: "Pirque", branch:santiago)
District.find_or_create_by(name: "Providencia", branch:santiago)
District.find_or_create_by(name: "Pudahuel", branch:santiago)
District.find_or_create_by(name: "Puente Alto", branch:santiago)
District.find_or_create_by(name: "Quilicura", branch:santiago)
District.find_or_create_by(name: "Quinta Normal", branch:santiago)
District.find_or_create_by(name: "Recoleta", branch:santiago)
District.find_or_create_by(name: "Renca", branch:santiago)
District.find_or_create_by(name: "San Bernardo", branch:santiago)
District.find_or_create_by(name: "San Joaquín", branch:santiago)
District.find_or_create_by(name: "San josé de Maipo", branch:santiago)
District.find_or_create_by(name: "San Miguel", branch:santiago)
District.find_or_create_by(name: "San Ramón", branch:santiago)
District.find_or_create_by(name: "Santiago", branch:santiago)
District.find_or_create_by(name: "Vitacura", branch:santiago)
District.find_or_create_by(name: "Otra comuna / cuidad", branch:santiago)

District.find_or_create_by(name: "Socabaya", branch:arequipa)
District.find_or_create_by(name: "Yanahuara", branch:arequipa)
District.find_or_create_by(name: "JLBYR", branch:arequipa)
District.find_or_create_by(name: "Pocsi", branch:arequipa)
District.find_or_create_by(name: "Arequipa", branch:arequipa)
District.find_or_create_by(name: "Cerro Colorado", branch:arequipa)
District.find_or_create_by(name: "Alto Selva Alegre", branch:arequipa)
District.find_or_create_by(name: "Cayma", branch:arequipa)
District.find_or_create_by(name: "Miraflores", branch:arequipa)
District.find_or_create_by(name: "Paucarpata", branch:arequipa)
District.find_or_create_by(name: "Characato", branch:arequipa)
District.find_or_create_by(name: "Hunter", branch:arequipa)
District.find_or_create_by(name: "La Joya", branch:arequipa)
District.find_or_create_by(name: "Mariano Melgar", branch:arequipa)
District.find_or_create_by(name: "Mollebaya", branch:arequipa)
District.find_or_create_by(name: "Polobaya", branch:arequipa)
District.find_or_create_by(name: "Quequeña", branch:arequipa)
District.find_or_create_by(name: "Sabandía", branch:arequipa)
District.find_or_create_by(name: "Sachaca", branch:arequipa)
District.find_or_create_by(name: "San Juan de Tarucani", branch:arequipa)
District.find_or_create_by(name: "Santa Isabel de Sihuas", branch:arequipa)
District.find_or_create_by(name: "Santa Rita de Sihuas", branch:arequipa)
District.find_or_create_by(name: "San Juan de Sihuas", branch:arequipa)
District.find_or_create_by(name: "Uchumayo", branch:arequipa)
District.find_or_create_by(name: "Tiabaya", branch:arequipa)
District.find_or_create_by(name: "Vitor", branch:arequipa)
District.find_or_create_by(name: "Yura", branch:arequipa)
District.find_or_create_by(name: "Tacna", branch:arequipa)
District.find_or_create_by(name: "Otra distrito / cuidad", branch:arequipa)

#Education types
Education.find_or_create_by(name: "Primaria incompleta", branch:lima)
Education.find_or_create_by(name: "Primaria completa", branch:lima)
Education.find_or_create_by(name: "Secundaria incompleta", branch:lima)
Education.find_or_create_by(name: "Secundaria completa", branch:lima)
Education.find_or_create_by(name: "Superior técnica incompleta", branch:lima)
Education.find_or_create_by(name: "Superior técnica completa (con título)", branch:lima)
Education.find_or_create_by(name: "Superior universitaria incompleta", branch:lima)
Education.find_or_create_by(name: "Superior universitaria completa (con título)", branch:lima)

Education.find_or_create_by(name: "Primaria incompleta", branch:mexico)
Education.find_or_create_by(name: "Primaria completa", branch:mexico)
Education.find_or_create_by(name: "Secundaria incompleta", branch:mexico)
Education.find_or_create_by(name: "Secundario completa", branch:mexico)
Education.find_or_create_by(name: "Prepa incompleta", branch:mexico)
Education.find_or_create_by(name: "Prepa completa", branch:mexico)
Education.find_or_create_by(name: "Superior técnica incompleta", branch:mexico)
Education.find_or_create_by(name: "Superior técnica completa (con título)", branch:mexico)
Education.find_or_create_by(name: "Superior universitaria incompleta", branch:mexico)
Education.find_or_create_by(name: "Superior universitaria completa (con título)", branch:mexico)

Education.find_or_create_by(name: "Básica incompleta", branch:santiago)
Education.find_or_create_by(name: "Básica completa", branch:santiago)
Education.find_or_create_by(name: "Media incompleta", branch:santiago)
Education.find_or_create_by(name: "Media completa", branch:santiago)
Education.find_or_create_by(name: "Superior técnica incompleta", branch:santiago)
Education.find_or_create_by(name: "Superior técnica completa (con título)", branch:santiago)
Education.find_or_create_by(name: "Superior universitaria incompleta", branch:santiago)
Education.find_or_create_by(name: "Superior universitaria completa (con título)", branch:santiago)

Education.find_or_create_by(name: "Primaria incompleta", branch:arequipa)
Education.find_or_create_by(name: "Primaria completa", branch:arequipa)
Education.find_or_create_by(name: "Secundaria incompleta", branch:arequipa)
Education.find_or_create_by(name: "Secundaria completa", branch:arequipa)
Education.find_or_create_by(name: "Superior técnica incompleta", branch:arequipa)
Education.find_or_create_by(name: "Superior técnica completa (con título)", branch:arequipa)
Education.find_or_create_by(name: "Superior universitaria incompleta", branch:arequipa)
Education.find_or_create_by(name: "Superior universitaria completa (con título)", branch:arequipa)

#Job Salaries
JobSalary.find_or_create_by(name: "Menos de 200 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 200 a 400 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 401 a 600 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 601 a 800 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 801 a 1000 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 1001 a 1200 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 1201 a 1400 soles", branch:lima)
JobSalary.find_or_create_by(name: "De 1401 a 1600 soles", branch:lima)
JobSalary.find_or_create_by(name: "Más de 1600 soles", branch:lima)

JobSalary.find_or_create_by(name: "Menos de $1000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $1,001 a $2,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $2,001 a $3,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $3,001 a $4,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $4,001 a $5,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $5,001 a $6,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $6,001 a $7,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $7,001 a $8,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $8,001 a $9,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "De $9,001 a $10,000 pesos", branch:mexico)
JobSalary.find_or_create_by(name: "Más de $10,000 pesos", branch:mexico)

JobSalary.find_or_create_by(name: "Menos de $50.000 pesos", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $50.001 y $100.000", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $100.001 y $200.000", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $200.001 y $300.000", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $300.001 y $400.000", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $400.001 y $500.000", branch:santiago)
JobSalary.find_or_create_by(name: "Entre $500.001 y $600.000", branch:santiago)
JobSalary.find_or_create_by(name: "Más de $600.000", branch:santiago)

JobSalary.find_or_create_by(name: "Menos de 200 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 200 a 400 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 401 a 600 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 601 a 800 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 801 a 1000 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 1001 a 1200 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 1201 a 1400 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "De 1401 a 1600 soles", branch:arequipa)
JobSalary.find_or_create_by(name: "Más de 1600 soles", branch:arequipa)

#Family incomes
FamilyIncome.find_or_create_by(name: "Menos de 800 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "De 800 a 1500 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "De 1501 a 2000 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "De 2001 a 2500 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "De 2501 a 3000 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "De 3001 a 3500 soles", branch:lima)
FamilyIncome.find_or_create_by(name: "Más de 3500 soles", branch:lima)

FamilyIncome.find_or_create_by(name: "Menos de $1000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $1,001 a $2,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $2,001 a $3,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $3,001 a $4,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $4,001 a $5,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $5,001 a $6,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $6,001 a $7,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $7,001 a $8,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $8,001 a $9,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $9,001 a $10,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $10,001 a $15,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $15,001 a $20,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $20,001 a $25,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "De $25,001 a $30,000 pesos", branch:mexico)
FamilyIncome.find_or_create_by(name: "Más de $30,000 pesos", branch:mexico)

FamilyIncome.find_or_create_by(name: "Menos de $100.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Entre $100.001 y $250.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Entre $250.001 y $400.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Entre $400.001 y $550.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Entre $500.001 y $700.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Entre $700.001 y $900.000", branch:santiago)
FamilyIncome.find_or_create_by(name: "Más de $900.001", branch:santiago)

FamilyIncome.find_or_create_by(name: "Menos de 800 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "De 800 a 1500 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "De 1501 a 2000 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "De 2001 a 2500 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "De 2501 a 3000 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "De 3001 a 3500 soles", branch:arequipa)
FamilyIncome.find_or_create_by(name: "Más de 3500 soles", branch:arequipa)

SemestersLeft.find_or_create_by(name: "1 ciclo", branch:lima)
SemestersLeft.find_or_create_by(name: "2 ciclos", branch:lima)
SemestersLeft.find_or_create_by(name: "3 ciclos", branch:lima)
SemestersLeft.find_or_create_by(name: "4 ciclos o más", branch:lima)
SemestersLeft.find_or_create_by(name: "Tesis", branch:lima)

SemestersLeft.find_or_create_by(name: "1 semestre", branch:mexico)
SemestersLeft.find_or_create_by(name: "2 semestres", branch:mexico)
SemestersLeft.find_or_create_by(name: "3 semestres", branch:mexico)
SemestersLeft.find_or_create_by(name: "4 semestres o más", branch:mexico)
SemestersLeft.find_or_create_by(name: "Tesis/Idioma/Servicio social", branch:mexico)

SemestersLeft.find_or_create_by(name: "1 Semestre", branch:santiago)
SemestersLeft.find_or_create_by(name: "2 Semestres", branch:santiago)
SemestersLeft.find_or_create_by(name: "3 Semestres", branch:santiago)
SemestersLeft.find_or_create_by(name: "4 Semestres o más", branch:santiago)
SemestersLeft.find_or_create_by(name: "Tesis / Examen de grado", branch:santiago)

SemestersLeft.find_or_create_by(name: "1 ciclo", branch:arequipa)
SemestersLeft.find_or_create_by(name: "2 ciclos", branch:arequipa)
SemestersLeft.find_or_create_by(name: "3 ciclos", branch:arequipa)
SemestersLeft.find_or_create_by(name: "4 ciclos o más", branch:arequipa)
SemestersLeft.find_or_create_by(name: "Tesis", branch:arequipa)

Spot.find_or_create_by(name: "Martes 22 de noviembre - 5:00pm a 9:00pm", branch:lima)
Spot.find_or_create_by(name: "Miércoles 23 de noviembre - 5:00pm a 9:00pm", branch:lima)
Spot.find_or_create_by(name: "Jueves 24 de noviembre - 5:00pm a 9:00pm", branch:lima)
Spot.find_or_create_by(name: "Sábado 26 de noviembre - 10:00am a 2:00pm", branch:lima)
Spot.find_or_create_by(name: "Sábado 26 de noviembre - 2:00pm a 6:00pm", branch:lima)
Spot.find_or_create_by(name: "Domingo 27 de noviembre - 10:00am a 2:00pm", branch:lima)
Spot.find_or_create_by(name: "Domingo 27 de noviembre - 2:00pm a 6:00pm", branch:lima)
Spot.find_or_create_by(name: "Martes 29 de noviembre - 5:00pm a 9:00pm", branch:lima)
Spot.find_or_create_by(name: "Miércoles 30 de noviembre - 5:00pm a 9:00pm", branch:lima)
Spot.find_or_create_by(name: "Jueves 01 de diciembre - 5:00pm a 9:00pm", branch:lima)

Spot.find_or_create_by(name: "Sábado 3 de diciembre - 8:30am a 1:00pm", branch:mexico)
Spot.find_or_create_by(name: "Sábado 3 de diciembre - 12:30pm a 5:00pm", branch:mexico)
Spot.find_or_create_by(name: "Domingo 4 de diciembre - 8:30am a 1:00pm", branch:mexico)
Spot.find_or_create_by(name: "Domingo 4 de diciembre - 12:30pm a 5:00pm", branch:mexico)
Spot.find_or_create_by(name: "Jueves 8 de diciembre - 5:30pm a 10:00pm", branch:mexico)
Spot.find_or_create_by(name: "Viernes 9 de diciembre - 5:30pm a 10:00pm", branch:mexico)
Spot.find_or_create_by(name: "Sábado 10 de diciembre - 8:30am a 1:00pm", branch:mexico)
Spot.find_or_create_by(name: "Sábado 10 de diciembre - 12:30pm a 5:00pm", branch:mexico)
Spot.find_or_create_by(name: "Domingo 11 de diciembre - 8:30am a 1:00pm", branch:mexico)
Spot.find_or_create_by(name: "Domingo 11 de diciembre - 12:30pm a 5:00pm", branch:mexico)

TechRelatedActivity.find_or_create_by(name: "Uso correo electrónico")
TechRelatedActivity.find_or_create_by(name: "Uso Google para investigar y conseguir respuestas")
TechRelatedActivity.find_or_create_by(name: "Soy activa en Facebook")
TechRelatedActivity.find_or_create_by(name: "Soy activa en otras redes sociales (aparte de Facebook)")
TechRelatedActivity.find_or_create_by(name: "Veo videos instructivos en Youtube u otro proveedor")
TechRelatedActivity.find_or_create_by(name: "Juego videojuegos")
TechRelatedActivity.find_or_create_by(name: "Soy seguidora de blogs")
TechRelatedActivity.find_or_create_by(name: "Escribo blogs")
TechRelatedActivity.find_or_create_by(name: "He hecho cursos en línea")
TechRelatedActivity.find_or_create_by(name: "Compro o reservo cosas por internet")
TechRelatedActivity.find_or_create_by(name: "Uso herramientas básicas como Microsoft Office (Word, Excel, Powerpoint)")
TechRelatedActivity.find_or_create_by(name: "He usado programas de diseño como Illustrator, Sketch o Photoshop")
TechRelatedActivity.find_or_create_by(name: "He aprendido temas relacionado a la programación, utilizando lenguajes como HTML, CCS, JS u otro")
TechRelatedActivity.find_or_create_by(name: "Me interesan otro tipo de actividades no relacionadas a la tecnología")
